{% set name = "jupyterlab_genv" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_genv-{{ version }}.tar.gz
  sha256: b05613722056130759f1181d7cf6dbd6aa77a3e31c9343919fec2dbc2b4d8b77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.3.1
    - jupyterlab ~=3.1
    - hatch-jupyter-builder >=0.5
  run:
    - python >=3.7
    - jupyter_server <2,>=1.6

test:
  imports:
    - jupyterlab_genv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyterlab-genv/
  summary: A JupyterLab extension for managing GPU environments using genv.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
